### ISSUE TITLE
IOS Safari/webview input:disabled时 颜色变浅的兼容

### ISSUE THREAD

**Issue by lovelmh13** [lovelmh13/myBlog#116]
1.设置 -webkit-text-fill-color

```css
input:disabled, input[disabled] {
  -webkit-text-fill-color: #2c363f;
  opacity: 1;
}
```

这时发现字体颜色和边框颜色都起作用了，但是还存在一个问题就是input 的placeholder 和颜色也被改成了 #2c363f 这个颜色，但是我们需要保持 placeholder 原来的颜色，于是还需要添加另外的css

2.设置 placeholder
```css
input[disabled]::placeholder {
  -webkit-text-fill-color: darkgray;
}
```

补充一些其他需注意的表单样式
```css
input, button, select, textarea {
  /*去掉ios阴影*/
  -webkit-appearance: none;
  /*去掉ios点击高亮*/
  -webkit-tap-highlight-color: transparent;
  /*聚焦时去掉轮廓*/
  outline: none;
  /*去掉边框*/
  border: none;
  
}

select, button {
  /*去掉灰色背景*/
  background: transparent;
}

textarea{
  /*禁止手动改变文本框大小*/
  resize: none;
}
```
