### ISSUE TITLE
input从右到左显示文字，并且光标始重在右侧。text-align和direction的区别

### ISSUE THREAD

**Issue by lovelmh13** [lovelmh13/myBlog#13]
其实很简单：
```css
.input {
    text-align: right
}
```
需要分清和`direction: rtl;`的区别

`text-align`是让文本靠右，而`direction: rtl;`是改变文本的方向

```html
<style type="text/css">
    div.one {
        text-align: right
    }
    div.two {
        direction: rtl;
    }
</style>

<div class="one">Some text. Right-to-left direction.</div>
<div class="two">Some text. Left-to-right direction.</div>
```

`.class`的显示效果只是让文字整体平移到右边
`.two`除了文字移到了右侧显示，文字也发生了改变。 会先成：`.Some text. Left-to-right direction`，看见区别了吗？句号位置变了。

经过我的测试，**如果只是改变文本内容**，`direction: rtl;`会改变符号和文字的位置，而文字如果也想从右往左写，只需要稍加改动，就可以把顺序完全颠倒，变成从右往左写：
```css 
div.two {
    direction: rtl;
    unicode-bidi:bidi-override;
}
```
就会变成：
`Some text. Left-to-right direction.`

 但是，**如果换成是input**，除了显示跟本文的显示方式一样以为，光标是不一样的。
`direction: rtl;` 因为是改文字方向，所以光标也改成了在左边。使用`backspace`和`delete`按键也会相反。
`text-align: right`是改变了文字的位置，而不是方向，光标是正常的，所以这个才是我们需要用的属性。
